version: '3.7'

services:
  database:
    image: mongo:latest
    container_name: mongo-database
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
